package main

import "fmt"

func printUsage() {
	fmt.Println("Atlas — Decision Intelligence Platform")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  atlas <command> [options]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  fetch             Run RSS collector daemon (scheduler loop)")
	fmt.Println("  analyze [flags]   Analyze articles via LLM")
	fmt.Println("  extract [flags]   Extract taxonomy entities from articles via LLM")
	fmt.Println("  evaluate [flags]  Evaluate extraction quality against golden dataset")
	fmt.Println("  benchmark [flags] Benchmark multiple providers against golden dataset")
	fmt.Println("  detect [flags]    Detect business signals from extraction results")
	fmt.Println("  classify [flags] <id>  Classify an article by UUID (industry, tech, country, stakeholder)")
	fmt.Println("  source <subcmd>   Source management (discover)")
	fmt.Println("  status [subcmd]   Show dashboard and reports")
	fmt.Println("  help              Show this help")
	fmt.Println()
	fmt.Println("source subcommands:")
	fmt.Println("  discover [flags] <url>  Probe a domain for RSS feeds and score it")
	fmt.Println()
	fmt.Println("classify flags:")
	fmt.Println("  --mock            Use MockClassifier instead of real LLM")
	fmt.Println("  --force           Re-classify even if already cached")
	fmt.Println()
	fmt.Println("analyze flags:")
	fmt.Println("  --once            Process available jobs and exit")
	fmt.Println("  --daemon          Run in continuous daemon mode (default: single run)")
	fmt.Println("  --enqueue         Enqueue new articles before processing")
	fmt.Println("  --max N           Maximum jobs to process (0 = all)")
	fmt.Println("  --mock            Use MockProvider instead of real LLM")
	fmt.Println("  --interval D      Poll interval for daemon mode (default: 60s)")
	fmt.Println("  --priority N      Priority for enqueued jobs (default: 5)")
	fmt.Println()
	fmt.Println("extract flags:")
	fmt.Println("  --once            Process available jobs and exit")
	fmt.Println("  --daemon          Run in continuous daemon mode (default: single run)")
	fmt.Println("  --enqueue         Enqueue new articles before processing")
	fmt.Println("  --max N           Maximum jobs to process (0 = all)")
	fmt.Println("  --mock            Use MockProvider instead of real LLM")
	fmt.Println("  --interval D      Poll interval for daemon mode (default: 60s)")
	fmt.Println("  --priority N      Priority for enqueued jobs (default: 5)")
	fmt.Println("  --article-id <id> Process a specific article by ID")
	fmt.Println()
	fmt.Println("evaluate flags:")
	fmt.Println("  --dataset <path>  Path to golden dataset JSON (default: testdata/golden-sample.json)")
	fmt.Println("  --mock            Use MockProvider instead of real LLM (default: true)")
	fmt.Println("  --format <fmt>    Output format: table, json (default: table)")
	fmt.Println()
	fmt.Println("benchmark flags:")
	fmt.Println("  --dataset <path>  Path to golden dataset JSON (default: testdata/golden-sample.json)")
	fmt.Println("  --providers <s>   Comma-separated providers: mock,anthropic,groq (default: mock,groq)")
	fmt.Println("  --models <s>      Comma-separated model names (overrides defaults)")
	fmt.Println()
	fmt.Println("detect flags:")
	fmt.Println("  --article-id <id> Process a specific article by ID")
	fmt.Println("  --all             Process all articles with extraction results")
	fmt.Println("  --max N           Maximum articles to process (0 = all)")
	fmt.Println()
	fmt.Println("status subcommands:")
	fmt.Println("  status            Show full dashboard")
	fmt.Println("  status sources    Show sources table")
	fmt.Println("  status logs [N]   Show N recent fetch logs (default: 20)")
	fmt.Println("  status reports [N] Show N intelligence reports (default: 20)")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  atlas fetch                        Start the RSS collector")
	fmt.Println("  atlas analyze --once --mock        Analyze with mock data")
	fmt.Println("  atlas analyze --once --enqueue     Analyze articles with real LLM")
	fmt.Println("  atlas analyze --daemon             Run analysis continuously")
	fmt.Println("  atlas status                       Show dashboard")
	fmt.Println("  atlas status reports 5             Show 5 intelligence reports")
}